name: Build LaTeX resume

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: resume.tex   # <-- change if your file is named differently
          latexmk_use_lualatex: false
          latexmk_use_xelatex: false
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf        # latex-action outputs resume.pdf by default
